name: Bug report
description: Report an issue
title: "[BUG] <title>"
labels: 'bug'
body:
  - type: markdown
    attributes:
      value: >-
        **This is a bug report, please only post issue in English.**

        Requests in other languages will be ignored and closed.

  - type: textarea
    id: what-happened
    attributes:
      label: 'What happened?'
      description: A clear and concise description of the issue.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 'What do you expect instead?'
      description: A clear and concise description of what you expect instead.
    validations:
      required: true

  - type: textarea
    id: repro-steps
    attributes:
      label: 'How to reproduce this issue?'
      description: A clear and concise description with precise steps to reproduce this issue.
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: 'Additional content:'
      description: Add any additional info, screenshots or recordings which help to describe the issue.
