name: Feature request
description: Suggest an idea or improvement
title: "[FR] <title>"
labels: 'enhancement'
body:
  - type: markdown
    attributes:
      value: >-
        **This is a feature request. Please describe your idea in English.**

        Requests in other languages will be ignored and closed.

  - type: textarea
    id: problem
    attributes:
      label: 'Is your feature request related to a problem? Please describe.'
      description: A clear and concise description of the problem you are facing. Example: "I’m always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 'Describe the solution you would like'
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 'Describe alternatives you’ve considered'
      description: A clear and concise description of any alternative solutions or features you have considered.
    validations:
      required: false

  - type: textarea
    id: additional-info
    attributes:
      label: 'Additional context'
      description: Add any other context, screenshots, or mockups about the feature request here.
